"""add phone

Revision ID: 1237da0ee581
Revises: f68b64bd1cd6
Create Date: 2022-07-18 14:13:08.395871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1237da0ee581'
down_revision = 'f68b64bd1cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('title', sa.String(length=125), nullable=False))
    op.add_column('complaints', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('complaints', 'Description')
    op.drop_column('complaints', 'Title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('Title', sa.VARCHAR(length=125), autoincrement=False, nullable=False))
    op.add_column('complaints', sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('complaints', 'description')
    op.drop_column('complaints', 'title')
    # ### end Alembic commands ###
